INSERT INTO OTHER_PRODUCT (PRODUCT_ID,COMPANY_NUMBER,RELEASE_DATE) VALUES(1,1,CURRENT_TIMESTAMP)
INSERT INTO OTHER_PRODUCT (PRODUCT_ID,COMPANY_NUMBER,RELEASE_DATE) VALUES(2,2,CURRENT_TIMESTAMP)
INSERT INTO OTHER_PRODUCT (PRODUCT_ID,COMPANY_NUMBER,RELEASE_DATE) VALUES(3,3,CURRENT_TIMESTAMP)
INSERT INTO OTHER_PRODUCT (PRODUCT_ID,COMPANY_NUMBER,RELEASE_DATE) VALUES(4,4,CURRENT_TIMESTAMP)

INSERT INTO OTHER_CATEGORY (CATEGORY_ID,TEST_PROPERTY_1,TEST_PROPERTY_2) VALUES(1001,'Phillip', 'Da Best')

INSERT INTO OTHER_SKU (SKU_ID,DETERMINED_PRICE) VALUES(1,18.98)